language: java
jdk:
  - oraclejdk8
services:
  - neo4j
sudo: true
env:
  - NEO4J_VERSION="3.1.1"
before_install:
  - nvm install 5.11.0
  - nvm use 5.11.0
  # install Neo4j manually:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d "password=root"