language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0
jdk:
  - oraclejdk7
env:
  - NEO4J_VERSION="3.1.1"
before_install:
    # install Neo4j locally:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start